# Generated by Django 4.2 on 2023-04-27 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contacts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t_id', models.IntegerField(max_length=8)),
                ('name', models.CharField(max_length=50)),
                ('case', models.CharField(max_length=50)),
                ('date', models.DateTimeField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('on progress', 'on Progress'), ('done', 'Done')], max_length=20)),
            ],
        ),
    ]
